In [3]:
import numpy as np
import requests
url = 'https://raw.githubusercontent.com/saadtony/NumericalMethods/master/styles/custom.css'
from IPython.core.display import HTML
def css_style():
    style = requests.get(url)
    return HTML(style.text)
css_style()

In [4]:
def jacobi2(A, xguess, b, tol):
    ''' Perform Jacobi iteration on the input parameters up to the specified tolerance.
    Convergence criteria is based on the L2 norm of the solution error b - Ax, where x is the 
    current iteration solution
    
    Inputs
    ------
    A: array, float -- A square matrix of the coefficients of the linear system
    b: array, float -- The solution vector
    xguess: array, float -- An initial input for the vector x
    tol: float -- The convergence tolerance
    
    Outputs
    ------- 
    xnew: array, float -- The vector x that solves the system
    '''
    nr, nc = A.shape
    if nr != nc:
        print('The coefficient matrix A must be a square matrix.')
        return None 
    err = np.inf
    xold = xguess.copy()
    xnew = np.empty(A.shape[1])
    count = 0
    while err > tol:
        for i in range(len(b)):
            xnew[i] = xold[i] + 1./A[i,i]*(b[i] - A[i]@xold)
        diff = b - A@xnew
        err = np.linalg.norm(diff, 2)
        xold = xnew.copy()
        count += 1
        print(f'Iteration: {count}, error norm = {err:.4f}')
    return xnew

In [5]:
A = np.array([[5,1,1],
             [2,3,0],
             [3,0,4]])
b = np.array([10, 11, 12])

In [6]:
np.linalg.solve(A, b)

array([0.93023256, 3.04651163, 2.30232558])

In [7]:
xguess = np.array([10.,20.,15.])

In [8]:
jacobi2(A, xguess, b, 1e-4)

Iteration: 1, error norm = 68.7841
Iteration: 2, error norm = 37.2936
Iteration: 3, error norm = 19.4888
Iteration: 4, error norm = 10.5665
Iteration: 5, error norm = 5.5218
Iteration: 6, error norm = 2.9938
Iteration: 7, error norm = 1.5645
Iteration: 8, error norm = 0.8483
Iteration: 9, error norm = 0.4433
Iteration: 10, error norm = 0.2403
Iteration: 11, error norm = 0.1256
Iteration: 12, error norm = 0.0681
Iteration: 13, error norm = 0.0356
Iteration: 14, error norm = 0.0193
Iteration: 15, error norm = 0.0101
Iteration: 16, error norm = 0.0055
Iteration: 17, error norm = 0.0029
Iteration: 18, error norm = 0.0015
Iteration: 19, error norm = 0.0008
Iteration: 20, error norm = 0.0004
Iteration: 21, error norm = 0.0002
Iteration: 22, error norm = 0.0001
Iteration: 23, error norm = 0.0001


array([0.93022696, 3.04650592, 2.30231916])

# Gauss-Seidel Iteration

The above code uses the Jacobi iteration method to solve a linear system. In Python, Jacobi has the advantage of being able to use NumPy vector operations, which are very fast. Jacobi does not use the most recent information when performing an iteration, however. Using updated information during iteration will increase the convergence speed, which is the method employed by Gauss-Seidel.

In [9]:
def gauss_seidel(A, xguess, b, tol):
    ''' Perform Gauss-Seidel iteration on the input parameters up to the specified tolerance.
    Convergence criteria is based on the L2 norm of the solution error b - Ax, where x is the 
    current iteration solution
    
    Inputs
    ------
    A: array, float -- A square matrix of the coefficients of the linear system
    b: array, float -- The solution vector
    xguess: array, float -- An initial input for the vector x
    tol: float -- The convergence tolerance
    
    Outputs
    ------- 
    x: array, float -- The vector x that solves the system
    '''
    nr, nc = A.shape
    if nr != nc:
        print('The coefficient matrix A must be a square matrix.')
        return None
    err = np.inf
    x = xguess.copy()
    count = 0
    while err > tol:
        for i in range(len(b)):
            x[i] = x[i] + 1./A[i,i]*(b[i] - A[i]@x)
        diff = b - A@x
        err = np.linalg.norm(diff, 2)
        count += 1
        print(f'Iteration: {count}, error norm = {err:.4f}')
    return x

In [10]:
gauss_seidel(A, xguess, b, 1e-4)

Iteration: 1, error norm = 21.2500
Iteration: 2, error norm = 6.0208
Iteration: 3, error norm = 1.7059
Iteration: 4, error norm = 0.4833
Iteration: 5, error norm = 0.1369
Iteration: 6, error norm = 0.0388
Iteration: 7, error norm = 0.0110
Iteration: 8, error norm = 0.0031
Iteration: 9, error norm = 0.0009
Iteration: 10, error norm = 0.0003
Iteration: 11, error norm = 0.0001


array([0.93021279, 3.04652481, 2.30234041])

In [16]:
def sor(A, xguess, b, ω,tol):
    ''' Perform succesive over-relaxation iteration on the input parameters up to the specified tolerance.
    Convergence criteria is based on the L2 norm of the solution error b - Ax, where x is the 
    current iteration solution
    
    Inputs
    ------
    A: array, float -- A square matrix of the coefficients of the linear system
    b: array, float -- The solution vector
    xguess: array, float -- An initial input for the vector x
    ω: float < 2.0 -- Relaxation parameter
    tol: float -- The convergence tolerance
    
    Outputs
    ------- 
    x: array, float -- The vector x that solves the system
    '''
    nr, nc = A.shape
    if nr != nc:
        print('The coefficient matrix A must be a square matrix.')
        return None
    err = np.inf
    x = xguess.copy()
    count = 0
    while err > tol:
        for i in range(len(b)):
            x[i] = x[i] + ω/A[i,i]*(b[i] - A[i]@x)
        diff = b - A@x
        err = np.linalg.norm(diff, 2)
        count += 1
        print(f'Iteration: {count}, error norm = {err:.4f}')
    return x

In [17]:
sor(A, xguess, b, 1.5, 1e-4)

Iteration: 1, error norm = 187.2997
Iteration: 2, error norm = 212.3990
Iteration: 3, error norm = 773.4471
Iteration: 4, error norm = 2325.8618
Iteration: 5, error norm = 4970.3667
Iteration: 6, error norm = 7934.3330
Iteration: 7, error norm = 8508.7106
Iteration: 8, error norm = 15350.7922
Iteration: 9, error norm = 58652.8603
Iteration: 10, error norm = 149365.9273
Iteration: 11, error norm = 277121.7408
Iteration: 12, error norm = 364258.5400
Iteration: 13, error norm = 436220.2231
Iteration: 14, error norm = 1618372.2146
Iteration: 15, error norm = 4771222.1815
Iteration: 16, error norm = 10177427.2010
Iteration: 17, error norm = 16088338.5038
Iteration: 18, error norm = 17121865.5937
Iteration: 19, error norm = 32003701.7211
Iteration: 20, error norm = 121242853.8071
Iteration: 21, error norm = 306417374.3232
Iteration: 22, error norm = 564551308.7995
Iteration: 23, error norm = 735618093.3516
Iteration: 24, error norm = 897418528.6549
Iteration: 25, error norm = 3357653999.4388

/Users/mattwilliams/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:28: RuntimeWarning: overflow encountered in matmul
/Users/mattwilliams/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:27: RuntimeWarning: overflow encountered in matmul
/Users/mattwilliams/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:27: RuntimeWarning: invalid value encountered in matmul
/Users/mattwilliams/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:28: RuntimeWarning: invalid value encountered in matmul


array([3.47261139e+307,            -inf,             nan])