In [1]:
import numpy as np
import requests
import matplotlib.pyplot as plt
from matplotlib import cm
from IPython.core.display import HTML
url = 'https://raw.githubusercontent.com/saadtony/NumericalMethods/master/styles/custom.css'
def css_style():
    response = requests.get(url)
    return HTML(response.text)
css_style()

In [25]:
def jacobi(A, xguess, b, maxIter, tol=None):
    if tol is None:
        tol = 1e-3
    [nr, nc] = A.shape
    iter = 0
    x = np.zeros(nc)
    err = np.inf
    while (iter < maxIter) and (err > tol):
        for i in range(0, nr):
            x[i] = xguess[i] + 1./A[i,i] * (b[i] - A[i]@xguess)
        err = xguess - x
        xguess = x.copy()
        err = np.linalg.norm(err)
        print(f'Iteration: {iter}, error: {err}')
        iter += 1
    while ()
    return x

In [9]:
A = np.array([[5.,1.,1.],
             [2.,3.,0.],
             [3.,0.,4.]])
A

array([[5., 1., 1.],
       [2., 3., 0.],
       [3., 0., 4.]])

In [10]:
b = np.array([10.,11.,12.])

In [11]:
np.linalg.solve(A,b)

array([0.93023256, 3.04651163, 2.30232558])

In [29]:
x = jacobi(A, np.array([0.,100.,0.]), b, 100)

Iteration: 0, error: 98.04647424110216
Iteration: 1, error: 25.974881028494515
Iteration: 2, error: 19.413247990247903
Iteration: 3, error: 7.359549624740114
Iteration: 4, error: 5.500420263903573
Iteration: 5, error: 2.085205727009699
Iteration: 6, error: 1.5584524081060118
Iteration: 7, error: 0.5908082893194142
Iteration: 8, error: 0.44156151563003654
Iteration: 9, error: 0.1673956819738344
Iteration: 10, error: 0.12510909609517704
Iteration: 11, error: 0.04742877655925271
Iteration: 12, error: 0.03544757722696655
Iteration: 13, error: 0.013438153358454868
Iteration: 14, error: 0.010043480214307099
Iteration: 15, error: 0.0038074767848955402
Iteration: 16, error: 0.0028456527273867894
Iteration: 17, error: 0.0010787850890530803
Iteration: 18, error: 0.0008062682727592248


In [30]:
x

array([0.9300098 , 3.04651893, 2.30233379])